env:
  browser: true
  es2021: true
  node: true
extends: 
  - eslint:recommended
  - prettier
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
plugins:
  - prettier
  - "@typescript-eslint"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  prettier/prettier:
    - error
  eqeqeq: 
    - error
    - always
  no-constant-condition:
    - off
  prefer-const: 
    - error
  no-fallthrough: 
    - off